apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-postgres
spec:
  selector:
    matchLabels:
      app: my-postgres
  template:
    metadata:
      labels:
        app: my-postgres
    spec:
      containers:
        - name: my-postgres
          image: postgres:13.2
          env:
            - name: POSTGRES_PASSWORD
              value: some_password
            - name: POSTGRES_USER
              value: some_user
            - name: POSTGRES_DB
              value: some_db
          ports:
            - containerPort: 5432
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: my-postgres
spec:
  selector:
    app: my-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP