apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  DB_HOST: amRiYzpwb3N0Z3Jlc3FsOi8vbXktcG9zdGdyZXMtcG9zdGdyZXNxbDo1NDMzL3NvbWVfZGI=
  DB_PORT: NTQzMw==
  DB_NAME: c29tZV9kYg==
  DB_USER: c29tZV91c2Vy
  DB_PASSWORD: c29tZV9wYXNzd29yZA==

---
apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-job
spec:
  template:
    spec:
      containers:
        - name: flyway-job
          image: 89629417575/lesson7-sql
          imagePullPolicy: Always
          env:
            - name: FLYWAY_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_HOST
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
      restartPolicy: Never
  backoffLimit: 4